//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTDlpSharp.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YTDlpSharp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse....
        /// </summary>
        internal static string BrowseButton_Text {
            get {
                return ResourceManager.GetString("BrowseButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FFmpeg was not found in your system PATH. Please install FFmpeg..
        /// </summary>
        internal static string DependencyCheck_FfmpegNotFound {
            get {
                return ResourceManager.GetString("DependencyCheck_FfmpegNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missing Dependencies.
        /// </summary>
        internal static string DependencyCheck_Title {
            get {
                return ResourceManager.GetString("DependencyCheck_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на yt-dlp was not found in your system PATH. Please install yt-dlp..
        /// </summary>
        internal static string DependencyCheck_YtdlpNotFound {
            get {
                return ResourceManager.GetString("DependencyCheck_YtdlpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        internal static string DownloadButton_Text {
            get {
                return ResourceManager.GetString("DownloadButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select download folder.
        /// </summary>
        internal static string FolderDialog_Title {
            get {
                return ResourceManager.GetString("FolderDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select download folder....
        /// </summary>
        internal static string FolderTextBox_PlaceholderText {
            get {
                return ResourceManager.GetString("FolderTextBox_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format:.
        /// </summary>
        internal static string FormatLabel_Text {
            get {
                return ResourceManager.GetString("FormatLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio only (best).
        /// </summary>
        internal static string FormatOption_AudioOnly {
            get {
                return ResourceManager.GetString("FormatOption_AudioOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video + audio (best quality).
        /// </summary>
        internal static string FormatOption_VideoAudioBest {
            get {
                return ResourceManager.GetString("FormatOption_VideoAudioBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video only (1080p if available).
        /// </summary>
        internal static string FormatOption_VideoOnly1080 {
            get {
                return ResourceManager.GetString("FormatOption_VideoOnly1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video only (480p).
        /// </summary>
        internal static string FormatOption_VideoOnly480 {
            get {
                return ResourceManager.GetString("FormatOption_VideoOnly480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video only (720p).
        /// </summary>
        internal static string FormatOption_VideoOnly720 {
            get {
                return ResourceManager.GetString("FormatOption_VideoOnly720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download complete!.
        /// </summary>
        internal static string Log_DownloadComplete {
            get {
                return ResourceManager.GetString("Log_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download failed.
        /// </summary>
        internal static string Log_DownloadFailed {
            get {
                return ResourceManager.GetString("Log_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error:.
        /// </summary>
        internal static string Log_ErrorPrefix {
            get {
                return ResourceManager.GetString("Log_ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting download....
        /// </summary>
        internal static string Log_StartingDownload {
            get {
                return ResourceManager.GetString("Log_StartingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste video URL here....
        /// </summary>
        internal static string UrlTextBox_PlaceholderText {
            get {
                return ResourceManager.GetString("UrlTextBox_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select a download folder.
        /// </summary>
        internal static string Validation_FolderRequired {
            get {
                return ResourceManager.GetString("Validation_FolderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a video URL.
        /// </summary>
        internal static string Validation_UrlRequired {
            get {
                return ResourceManager.GetString("Validation_UrlRequired", resourceCulture);
            }
        }
    }
}
